# Generated by Django 5.2.17 on 2026-08-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='user-avatars/%Y/%m/', verbose_name='头像'),
        ),
    ]
