# Generated by Django 5.2.17 on 2026-08-28 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=120, unique=True, verbose_name='项目 ID')),
                ('category', models.CharField(db_index=True, max_length=64, verbose_name='分类')),
                ('group', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='子分类')),
                ('zh_title', models.CharField(max_length=160, verbose_name='中文标题')),
                ('en_title', models.CharField(max_length=200, verbose_name='英文标题')),
                ('zh_description', models.TextField(blank=True, verbose_name='中文说明')),
                ('en_description', models.TextField(blank=True, verbose_name='英文说明')),
                ('prompt', models.TextField(verbose_name='提示词')),
                ('image', models.CharField(blank=True, max_length=500, verbose_name='内置效果图路径')),
                ('uploaded_image', models.ImageField(blank=True, upload_to='catalog/featured/', verbose_name='替换效果图')),
                ('original_image', models.CharField(blank=True, max_length=500, verbose_name='内置原图路径')),
                ('uploaded_original_image', models.ImageField(blank=True, upload_to='catalog/featured/original/', verbose_name='替换原图')),
                ('result_image', models.CharField(blank=True, max_length=500, verbose_name='内置结果图路径')),
                ('uploaded_result_image', models.ImageField(blank=True, upload_to='catalog/featured/result/', verbose_name='替换结果图')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '精选提示词',
                'verbose_name_plural': '精选提示词',
                'ordering': ('category', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ParameterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=120, unique=True, verbose_name='参数 ID')),
                ('category', models.CharField(db_index=True, max_length=64, verbose_name='分类')),
                ('style_group', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='子分类')),
                ('zh_name', models.CharField(max_length=120, verbose_name='中文名称')),
                ('en_name', models.CharField(max_length=160, verbose_name='英文名称')),
                ('image', models.CharField(blank=True, max_length=500, verbose_name='内置图片路径')),
                ('uploaded_image', models.ImageField(blank=True, upload_to='catalog/parameters/', verbose_name='替换图片')),
                ('zh_prompt', models.TextField(verbose_name='中文提示词')),
                ('en_prompt', models.TextField(verbose_name='英文提示词')),
                ('negative', models.JSONField(blank=True, default=list, verbose_name='负面词')),
                ('default_weight', models.DecimalField(decimal_places=1, default=1, max_digits=3, verbose_name='默认权重')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '参数选项',
                'verbose_name_plural': '参数选项',
                'ordering': ('category', 'order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='建议内容')),
                ('image', models.ImageField(blank=True, upload_to='feedback/%Y/%m/', verbose_name='附件图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('handled', models.BooleanField(default=False, verbose_name='已处理')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '意见建议',
                'verbose_name_plural': '意见建议',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='模板名称')),
                ('preview_image', models.ImageField(blank=True, upload_to='user-templates/%Y/%m/', verbose_name='展示图片')),
                ('configuration', models.JSONField(default=dict, verbose_name='选择配置')),
                ('prompt_zh', models.TextField(blank=True, verbose_name='中文提示词')),
                ('prompt_en', models.TextField(blank=True, verbose_name='英文提示词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_templates', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户模板',
                'verbose_name_plural': '用户模板',
                'ordering': ('-updated_at',),
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='unique_template_name_per_owner')],
            },
        ),
    ]
