# Generated by Django 5.2.17 on 2026-08-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameteroption',
            name='default_weight',
        ),
        migrations.AlterField(
            model_name='featuredprompt',
            name='image',
            field=models.CharField(blank=True, max_length=500, verbose_name='内置展示图地址'),
        ),
        migrations.AlterField(
            model_name='featuredprompt',
            name='original_image',
            field=models.CharField(blank=True, max_length=500, verbose_name='内置原图地址'),
        ),
        migrations.AlterField(
            model_name='featuredprompt',
            name='result_image',
            field=models.CharField(blank=True, max_length=500, verbose_name='内置效果图地址'),
        ),
        migrations.AlterField(
            model_name='featuredprompt',
            name='uploaded_image',
            field=models.ImageField(blank=True, upload_to='catalog/featured/', verbose_name='上传展示图'),
        ),
        migrations.AlterField(
            model_name='featuredprompt',
            name='uploaded_original_image',
            field=models.ImageField(blank=True, upload_to='catalog/featured/original/', verbose_name='上传原图'),
        ),
        migrations.AlterField(
            model_name='featuredprompt',
            name='uploaded_result_image',
            field=models.ImageField(blank=True, upload_to='catalog/featured/result/', verbose_name='上传效果图'),
        ),
        migrations.AlterField(
            model_name='parameteroption',
            name='image',
            field=models.CharField(blank=True, max_length=500, verbose_name='内置资源地址'),
        ),
        migrations.AlterField(
            model_name='parameteroption',
            name='uploaded_image',
            field=models.ImageField(blank=True, upload_to='catalog/parameters/', verbose_name='上传图片'),
        ),
    ]
