# Generated by Django 5.2.17 on 2026-08-28 08:28

from django.db import migrations, models


def normalize_scoped_order(apps, schema_editor):
    configurations = (
        (apps.get_model("content", "ParameterOption"), "style_group"),
        (apps.get_model("content", "FeaturedPrompt"), "group"),
    )
    for model, group_field in configurations:
        scopes = model.objects.order_by().values_list("category", group_field).distinct()
        for category, group in scopes:
            items = list(
                model.objects.filter(category=category, **{group_field: group}).order_by("order", "id")
            )
            for index, item in enumerate(items, start=1):
                item.order = index
            if items:
                model.objects.bulk_update(items, ("order",))


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_parameteroption_default_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredprompt',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='仅在当前分类和子分类内排序；保存后由后台自动整理为连续序号。', verbose_name='板块内排序'),
        ),
        migrations.AlterField(
            model_name='featuredprompt',
            name='source_id',
            field=models.CharField(blank=True, editable=False, max_length=120, unique=True, verbose_name='项目 ID'),
        ),
        migrations.AlterField(
            model_name='parameteroption',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='仅在当前分类和子分类内排序；保存后由后台自动整理为连续序号。', verbose_name='板块内排序'),
        ),
        migrations.AlterField(
            model_name='parameteroption',
            name='source_id',
            field=models.CharField(blank=True, editable=False, max_length=120, unique=True, verbose_name='项目 ID'),
        ),
        migrations.RunPython(normalize_scoped_order, migrations.RunPython.noop),
    ]
