# Generated by Django 5.2.17 on 2026-08-28 13:08

from django.db import migrations, models


def create_default_site_settings(apps, schema_editor):
    apps.get_model("content", "SiteSettings").objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_require_and_classify_subcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='图片提示词生成器', max_length=80, verbose_name='网站名称')),
                ('logo', models.ImageField(blank=True, upload_to='site/', verbose_name='网站 Logo')),
                ('wechat_qr', models.ImageField(blank=True, upload_to='site/', verbose_name='微信群二维码')),
                ('help_text', models.CharField(default='需要帮助？扫码加入微信群', max_length=160, verbose_name='帮助提示')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
        migrations.RunPython(create_default_site_settings, migrations.RunPython.noop),
    ]
