# Generated by Django 5.2.17 on 2026-08-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='slogan',
            field=models.CharField(default='词出新意，图出惊喜', max_length=120, verbose_name='品牌口号'),
        ),
    ]
